# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a4030ece5eeb941418d53e2f8fdff4f96eb499dcdcd25c90ace5cb2ff4e56c491f6513b215b578854114a1667705812b0e92e619644ed3823a9b33e823e405

test:
  secret_key_base: 610de85e419f5a622f9f05102a6d2393e23ba2941bf31e4007a85b082a563acf47852bff6135122da3b3b85c77b25e755555ceb7e3220e31c7621f1417401e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
